apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-example
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: node-example
    spec:
      containers:
      - name: node-example
        image: shrikanth24/samplenode2
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
-----
apiVersion: v1
kind: Service
metadata:
  name: node-example
  labels:
    app: node-example
spec:
  selector:
    app: node-example
  ports:
  - port: 3000
    protocol: TCP
    nodePort: 30001
  type: LoadBalancer